const fs = require('fs');

const examples = {
  "reach out": "If you have any questions, don't hesitate to reach out to me. - Eğer herhangi bir sorunuz olursa, bana ulaşmaktan çekinmeyin.",
  "criticise": "It is unfair to criticise him without knowing the full story. - Tüm hikayeyi bilmeden onu eleştirmek haksızlıktır.",
  "memorise": "I need to memorise these new vocabulary words before the test. - Sınavdan önce bu yeni kelimeleri ezberlemem gerekiyor.",
  "common": "Traffic congestion is a common problem in big cities. - Trafik sıkışıklığı büyük şehirlerde ortak bir sorundur.",
  "exist": "Many people wonder if life could exist on other planets. - Çoğu insan başka gezegenlerde yaşamın var olup olamayacağını merak ediyor.",
  "develop": "Reading regularly can help you develop your language skills. - Düzenli okumak dil becerilerinizi geliştirmenize yardımcı olabilir.",
  "fluent": "She lived in London for five years, so she is completely fluent. - Londra'da beş yıl yaşadı, bu yüzden tamamen akıcı konuşuyor.",
  "agree": "I completely agree with your opinion on this matter. - Bu konudaki fikrine tamamen katılıyorum.",
  "neither": "I don't like coffee, and neither does my brother. - Ben kahve sevmem, kardeşim de sevmez.",
  "press": "Please press the red button to start the machine. - Makineyi başlatmak için lütfen kırmızı tuşa basın.",
  "undo": "Is there a way to undo this action on the computer? - Bilgisayarda bu işlemi geri almanın bir yolu var mı?",
  "charge": "I forgot to charge my phone, so the battery is dead. - Telefonumu şarj etmeyi unuttum, bu yüzden şarjı bitti.",
  "business contract": "They signed a new business contract with an international firm. - Uluslararası bir firmayla yeni bir iş sözleşmesi imzaladılar.",
  "make contact": "We are trying to make contact with the manager to discuss the issue. - Sorunu görüşmek üzere yöneticiyle temas kurmaya çalışıyoruz.",
  "emphasis": "The teacher put a strong emphasis on speaking practice. - Öğretmen konuşma pratiğine güçlü bir vurgu yaptı.",
  "successful": "She became a very successful entrepreneur in a short time. - Kısa sürede çok başarılı bir girişimci oldu.",
  "talented": "He is a talented musician who plays three different instruments. - Üç farklı enstrüman çalan yetenekli bir müzisyendir.",
  "intelligent": "Dolphins are known to be highly intelligent animals. - Yunusların son derece zeki hayvanlar olduğu bilinmektedir.",
  "confident": "You need to be confident during your job interview. - İş görüşmende öz güvenli olman gerekiyor.",
  "determined": "Despite the difficulties, she remained determined to win the race. - Zorluklara rağmen, yarışı kazanmakta kararlı kaldı.",
  "achievement": "Graduating from university was her greatest achievement. - Üniversiteden mezun olmak onun en büyük başarısıydı.",
  "attitude": "Having a positive attitude can change your whole life. - Pozitif bir tutuma sahip olmak tüm hayatınızı değiştirebilir.",
  "give up": "No matter how hard it gets, you should never give up. - Ne kadar zorlaşırsa zorlaşsın, asla vazgeçmemelisin.",
  "sociable": "My sister is very sociable and loves meeting new people. - Kız kardeşim çok sosyaldir ve yeni insanlarla tanışmayı sever.",
  "outgoing": "He has an outgoing personality and easily makes friends. - Uyumlu ve dışa dönük bir kişiliği var ve kolayca arkadaş edinir.",
  "talkative": "She is usually quiet, but she gets talkative when she is excited. - Genelde sessizdir ama heyecanlandığında konuşkan olur.",
  "shy": "The little boy was too shy to speak to the guests. - Küçük çocuk misafirlerle konuşamayacak kadar utangaçtı.",
  "reserved": "He is a reserved person who rarely shares his feelings. - Duygularını nadiren paylaşan, duygu belli etmeyen biridir.",
  "lively": "The city center is always lively and full of energy. - Şehir merkezi her zaman canlı ve enerji doludur.",
  "serious": "We need to have a serious conversation about your future. - Geleceğin hakkında ciddi bir konuşma yapmamız gerekiyor.",
  "sensitive": "My skin is very sensitive to sunlight. - Cildim güneş ışığına karşı çok hassas.",
  "valued": "As a member of this team, your opinions are highly valued. - Bu takımın bir üyesi olarak, fikirleriniz oldukça değerlidir.",
  "movement": "There is a growing movement to protect the environment. - Çevreyi korumak için büyüyen bir eylem var.",
  "despite": "He went to work despite being very ill. - Çok hasta olmasına rağmen işe gitti.",
  "songwriters": "The most successful songwriters often write from their own experiences. - En başarılı söz yazarları genellikle kendi deneyimlerinden yazarlar.",
  "bright": "She is a bright student who always gets the highest grades. - O, her zaman en yüksek notları alan zeki bir öğrencidir.",
  "towards": "The dog ran towards me as soon as I opened the gate. - Kapıyı açar açmaz köpek bana karşı koştu.",
  "ability": "He has the ability to learn new languages very quickly. - Yeni dilleri çok hızlı öğrenme yeteneğine sahiptir.",
  "pick up": "Can you pick up the package from the post office? - Postaneden paketi teslim alabilir misin?",
  "pollution": "Air pollution is a major problem in industrial cities. - Hava kirliliği sanayi şehirlerinde büyük bir sorundur.",
  "endangered": "Pandas are considered an endangered species. - Pandalar tehlikede olan bir tür olarak kabul edilir.",
  "damaged": "The storm damaged several houses in the neighborhood. - Fırtına mahalledeki birkaç eve zarar verdi.",
  "protect": "We must protect the forests for future generations. - Gelecek nesiller için ormanları korumalıyız.",
  "environment": "It is our responsibility to take care of the environment. - Çevreye iyi bakmak bizim sorumluluğumuzdur.",
  "creature": "The deep ocean is home to many strange creatures. - Derin okyanus birçok tuhaf yaratığa ev sahipliği yapar.",
  "destroy": "The earthquake could destroy the entire city. - Deprem tüm şehri yerle bir edebilir.",
  "species": "There are thousands of different species of birds in the world. - Dünyada binlerce farklı kuş türü bulunmaktadır.",
  "survive": "Camels can survive in the desert without water for days. - Develer çölde günlerce susuz hayatta kalabilirler.",
  "limit": "We should limit the amount of sugar we eat every day. - Her gün yediğimiz şeker miktarını sınırlamalıyız.",
  "branch": "The bird built its nest on a high branch of the tree. - Kuş yuvasını ağacın yüksek bir dalına yaptı.",
  "petals": "The rose had beautiful red petals. - Gülün güzel kırmızı taç yaprakları vardı.",
  "feathers": "The parrot has brightly colored feathers. - Papağanın parlak renkli tüyleri vardır.",
  "scales": "Fish are covered in scales to protect their bodies. - Balıklar vücutlarını korumak için pullarla kaplıdır.",
  "fur": "Cats have soft fur that keeps them warm in winter. - Kedilerin kışın onları sıcak tutan yumuşak kürkleri vardır.",
  "bay": "They rented a small boat to sail around the bay. - Koyun etrafında yelken açmak için küçük bir tekne kiraladılar.",
  "waterfall": "We hiked for hours just to see the beautiful waterfall. - Sadece güzel şelaleyi görmek için saatlerce yürüdük.",
  "cave": "The explorers found ancient drawings inside the dark cave. - Kaşifler karanlık mağaranın içinde antik çizimler buldular.",
  "paws": "The dog left muddy paws all over the clean floor. - Köpek temiz zeminin her yerinde çamurlu pati izleri bıraktı.",
  "web": "The spider spun a complex web in the corner of the room. - Örümcek odanın köşesinde karmaşık bir ağ ördü.",
  "hook": "He used a sharp hook to catch the large fish. - Büyük balığı yakalamak için keskin bir kanca kullandı.",
  "sticking": "The glue is sticking the pieces of paper together perfectly. - Yapıştırıcı kağıt parçalarını birbirine mükemmel bir şekilde yapıştırıyor.",
  "arctic": "Polar bears live in the freezing cold conditions of the arctic. - Kutup ayıları kutbun dondurucu soğuk koşullarında yaşarlar.",
  "inspire": "Her speech will inspire many young artists to follow their dreams. - Onun konuşması birçok genç sanatçıya hayallerinin peşinden gitmeleri için ilham alacaktır.",
  "seeds": "We planted some seeds in the garden and waited for them to grow. - Bahçeye biraz tohum ektik ve büyümelerini bekledik.",
  "rose": "He gave her a single red rose on their anniversary. - Yıl dönümlerinde ona tek bir kırmızı gül verdi.",
  "pine tree": "The forest was full of tall pine trees that smelled wonderful. - Orman harika kokan uzun çam ağaçlarıyla doluydu.",
  "souvenir shop": "We bought some gifts for our friends from the souvenir shop. - Hediyelik eşya dükkanından arkadaşlarımız için bazı hediyeler aldık.",
  "bottle opener": "Can you pass me the bottle opener so I can open this drink? - Bu içeceği açabilmem için bana şişe açacağını uzatır mısın?",
  "window seat": "I always request a window seat when I fly so I can see the clouds. - Uçtuğumda her zaman cam kenarı isterim böylece bulutları görebilirim.",
  "dishwasher": "Please put your dirty plates in the dishwasher after dinner. - Lütfen akşam yemeğinden sonra kirli tabaklarını bulaşık makinesine koy.",
  "insect repellent": "Don't forget to use insect repellent to keep the mosquitoes away. - Sivrisinekleri uzak tutmak için böcek savar kullanmayı unutma.",
  "insights": "The documentary provided deep insights into the lives of wild animals. - Belgesel vahşi hayvanların yaşamlarının iç yüzünü anlamak için derin bilgiler sundu.",
  "approach to": "We need to find a new approach to solving this math problem. - Bu matematik problemini çözmek için yeni bir yaklaşım bulmalıyız.",
  "vaccinations": "Make sure you get all your travel vaccinations before visiting the country. - Ülkeyi ziyaret etmeden önce tüm seyahat aşılarınızı yaptırdığınızdan emin olun.",
  "plantain": "She fried some plantain to serve with the main dish. - Ana yemekle servis etmek için biraz muz türü (plantain) kızarttı.",
  "contribute": "Everyone should contribute ideas during the brainstorming session. - Beyin fırtınası oturumu sırasında herkes fikirlere katkıda bulunmalıdır.",
  "herbs": "Adding fresh herbs like basil and mint makes the soup taste better. - Fesleğen ve nane gibi taze bitkiler eklemek çorbanın tadını güzelleştirir.",
  "mention": "Did he mention what time the meeting is going to start? - Toplantının saat kaçta başlayacağından bahsetti mi?",
  "in advance": "You need to book your train tickets weeks in advance. - Tren biletlerinizi haftalar önceden ayırtmanız gerekiyor.",
  "steamed rice": "I ordered a bowl of steamed rice to go with the spicy chicken. - Baharatlı tavuğun yanına bir kase buharda pilav sipariş ettim.",
  "randomly": "The teacher randomly picked a student to answer the question. - Öğretmen soruyu cevaplaması için rastgele bir öğrenci seçti.",
  "explore": "We spent the whole afternoon trying to explore the historical ruins. - Bütün öğleden sonrayı tarihi kalıntıları keşfetmeye çalışarak geçirdik.",
  "bride": "The bride looked stunning in her elegant white dress. - Gelin zarif beyaz elbisesi içinde çarpıcı görünüyordu.",
  "groom": "The groom waited nervously at the altar for the ceremony to begin. - Damat törenin başlaması için mihrapta gergin bir şekilde bekledi.",
  "moving house": "We are moving house next week, so we are busy packing boxes. - Haftaya ev taşıyoruz, bu yüzden kutuları paketlemekle meşgulüz.",
  "move out of": "He decided to move out of his parents' house and live on his own. - Ailesinin evinden çıkmaya ve kendi başına yaşamaya karar verdi.",
  "terrace": "We sat on the terrace enjoying the beautiful sunset. - Güzel gün batımının tadını çıkararak terasta oturduk.",
  "renting": "Renting an apartment in the city center is becoming very expensive. - Şehir merkezinde bir daire kiralamak çok pahalı hale geliyor.",
  "block": "They live in the modern block of apartments at the end of the street. - Sokağın sonundaki modern apartman bloğunda yaşıyorlar.",
  "neighbourhood": "We live in a quiet and friendly neighbourhood. - Sessiz ve samimi bir mahallede yaşıyoruz.",
  "ground floor": "Our office is located on the ground floor of the building. - Ofisimiz binanın zemin katında yer almaktadır.",
  "landing": "She waited for him on the landing at the top of the stairs. - Merdivenlerin başındaki sahanlıkta onu bekledi.",
  "argue with": "I don't want to argue with you over such a small mistake. - Böyle küçük bir hata yüzünden seninle tartışmak istemiyorum.",
  "cope with": "It can be difficult to cope with stress during exam week. - Sınav haftasında stresle başa çıkmak zor olabilir.",
  "care about": "Good teachers deeply care about the success of their students. - İyi öğretmenler öğrencilerinin başarısını derinden umursarlar.",
  "worry about": "You shouldn't worry about things you cannot control. - Kontrol edemeyeceğin şeyler için endişelenmemelisin.",
  "complain about": "Customers often complain about the slow service in this restaurant. - Müşteriler genellikle bu restorandaki yavaş servisten şikayet ederler.",
  "rely on": "You can always rely on me if you need any support. - Herhangi bir desteğe ihtiyacın olursa her zaman bana güvenebilirsin.",
  "depend on": "The success of the project will depend on how hard we work. - Projenin başarısı ne kadar sıkı çalıştığımıza bağlı olacak.",
  "apologise for": "I must apologise for arriving late to the dinner. - Akşam yemeğine geç geldiğim için özür dilemeliyim.",
  "believe in": "If you believe in yourself, you can achieve anything. - Kendine inanırsan, her şeyi başarabilirsin.",
  "succeed in": "She worked hard to succeed in passing the advanced English exam. - İleri düzey İngilizce sınavını geçmeyi başarmak için çok çalıştı.",
  "belong to": "Does this black umbrella belong to anyone in the office? - Bu siyah şemsiye ofisteki herhangi birine ait mi?",
  "apologise to": "You should apologise to your sister for breaking her toy. - Oyuncağını kırdığın için kız kardeşinden özür dilemelisin.",
  "complain to": "If the hotel room is dirty, you should complain to the manager. - Eğer otel odası kirliyse, yöneticiye şikayet etmelisin.",
  "outskirts": "They bought a quiet house on the outskirts of the city. - Şehrin eteklerinde sessiz bir ev aldılar.",
  "entire": "I was so hungry that I ate the entire pizza by myself. - O kadar açtım ki pizzanın tamamını tek başıma yedim.",
  "accommodation": "We need to find cheap accommodation for our trip to London. - Londra seyahatimiz için ucuz bir konaklama bulmalıyız.",
  "range": "The store offers a wide range of organic products. - Mağaza geniş bir organik ürün aralığı sunuyor.",
  "hosts": "Our hosts were very welcoming and made us feel at home. - Ev sahiplerimiz çok misafirperverdi ve bizi evimizde hissettirdi.",
  "nearby": "There is a great cafe nearby where we can grab a coffee. - Yakınlarda kahve alabileceğimiz harika bir kafe var.",
  "theft": "He reported the theft of his bicycle to the local police. - Bisikletinin hırsızlığını yerel polise bildirdi.",
  "create": "The artist used recycled materials to create a beautiful sculpture. - Sanatçı güzel bir heykel yaratmak için geri dönüştürülmüş malzemeler kullandı.",
  "hold a meeting": "We will hold a meeting tomorrow to discuss the new project. - Yeni projeyi tartışmak için yarın toplantı yapacağız.",
  "subscriber": "He is a loyal subscriber to several tech magazines. - O, birkaç teknoloji dergisine sadık bir abonedir.",
  "series": "I spent the whole weekend watching a new drama series on TV. - Bütün hafta sonunu televizyonda yeni bir drama dizisi izleyerek geçirdim.",
  "episode": "The final episode of the show was full of surprising twists. - Şovun son bölümü şaşırtıcı olaylarla doluydu.",
  "deliver": "The courier will deliver the package to your house tomorrow morning. - Kurye paketi yarın sabah evinize teslim edecek.",
  "post on": "Don't forget to post on social media to announce the event. - Etkinliği duyurmak için sosyal medyada gönderi paylaşmayı unutma.",
  "advise": "I strongly advise you to study hard before the final exams. - Final sınavlarından önce sıkı çalışmanı şiddetle tavsiye ederim.",
  "were offering": "They were offering a massive discount on all electronics yesterday. - Dün tüm elektronik ürünlerde büyük bir teklif yapıyorlardı.",
  "warn": "I must warn you that the roads are very icy today. - Bugün yolların çok buzlu olduğu konusunda seni uyarmalıyım.",
  "promise": "I promise to call you as soon as I arrive at the station. - İstasyona varır varmaz seni arayacağıma söz veriyorum.",
  "recommend": "Can you recommend a good restaurant for our anniversary dinner? - Yıl dönümü yemeğimiz için iyi bir restoran tavsiye edebilir misin?",
  "threaten": "The storm began to threaten the small coastal village. - Fırtına küçük sahil köyünü tehdit etmeye başladı.",
  "offer": "They decided to offer him the job because of his excellent skills. - Mükemmel becerilerinden dolayı ona işi teklif etmeye karar verdiler.",
  "suggest": "I suggest that we leave early to avoid the heavy traffic. - Yoğun trafikten kaçınmak için erken çıkmamızı öneriyorum.",
  "attend": "All students must attend the lecture on Monday morning. - Tüm öğrenciler pazartesi sabahı derse katılmalıdır.",
  "basis": "They meet on a regular basis to practice their English speaking. - İngilizce konuşma pratikleri yapmak için düzenli bir temel üzerinde buluşuyorlar.",
  "come across": "I happened to come across an old friend while walking in the park. - Parkta yürürken tesadüfen eski bir arkadaşla karşılaştım.",
  "genuine": "Her smile showed that she had a genuine interest in the topic. - Gülümsemesi konuya karşı gerçek bir ilgisi olduğunu gösterdi.",
  "kept": "He kept the secret to himself for many years. - Sırrını uzun yıllar kendine sakladı (tuttu).",
  "submitted": "All applications must be submitted by the end of the week. - Tüm başvurular hafta sonuna kadar teslim edilmelidir.",
  "setting up": "They are setting up the stage for tonight's concert. - Bu geceki konser için sahneyi kuruyorlar.",
  "get through": "It was a tough time, but we managed to get through it together. - Zor bir dönemdi, ama birlikte atlatmayı başardık.",
  "according to": "According to the weather forecast, it will rain tomorrow. - Hava tahminlerine göre, yarın yağmur yağacak.",
  "wished": "I wished I had studied harder for the math exam. - Keşke matematik sınavına daha çok çalışsaydım diye diledim.",
  "enquiries": "For any further enquiries, please contact the main office. - Daha fazla soruşturma için lütfen ana ofisle iletişime geçin.",
  "pretending": "The kids were pretending to be brave explorers in the jungle. - Çocuklar ormanda cesur kaşiflermiş gibi yapıyorlardı.",
  "believe to": "This painting is widely believe to be the work of a famous artist. - Bu tablonun yaygın olarak ünlü bir sanatçının eseri olduğuna inanılır.",
  "disappointed": "I was very disappointed when my favorite team lost the match. - Favori takımım maçı kaybettiğinde çok hayal kırıklığına uğradım.",
  "disappointing": "The ending of the movie was quite disappointing. - Filmin sonu oldukça hayal kırıklığı yaratıcıydı.",
  "amused": "The children were highly amused by the clown's funny tricks. - Çocuklar palyaçonun komik numaralarıyla çok eğlenmişlerdi.",
  "amusing": "He told us an amusing story about his travel adventures. - Bize seyahat maceraları hakkında eğlenceli bir hikaye anlattı.",
  "depressed": "She felt depressed after failing the important driving test. - Önemli direksiyon sınavında başarısız olduktan sonra depresif hissetti.",
  "depressing": "The constant rain all week was really depressing. - Bütün hafta süren sürekli yağmur gerçekten üzücüydü.",
  "character": "He is the main character in the newly released novel. - Yeni yayımlanan romanın ana karakteri o.",
  "event": "The annual sports event attracts athletes from all over the country. - Yıllık spor etkinliği ülkenin dört bir yanından sporcuları çeker.",
  "gulf": "The ship sailed smoothly across the calm waters of the gulf. - Gemi körfezin sakin sularında pürüzsüzce ilerledi.",
  "profits": "The company saw a huge increase in its profits this year. - Şirket bu yıl kârında büyük bir artış gördü.",
  "charity": "She donated all of her old clothes to a local charity. - Tüm eski kıyafetlerini yerel bir hayır kurumuna bağışladı.",
  "beauty": "The natural beauty of the national park is truly breathtaking. - Milli parkın doğal güzelliği gerçekten nefes kesicidir.",
  "celebration": "We are having a big celebration for his retirement next week. - Haftaya onun emekliliği için büyük bir kutlama yapıyoruz.",
  "celebrate": "How do you usually celebrate your birthday with your friends? - Doğum gününü arkadaşlarınla genelde nasıl kutlarsın?",
  "charitable": "They do a lot of charitable work to help the homeless. - Evsizlere yardım etmek için çok sayıda hayırsever iş yaparlar.",
  "creative": "She is a creative designer who always comes up with unique ideas. - O, her zaman eşsiz fikirler bulan yaratıcı bir tasarımcıdır.",
  "creativity": "Writing a good story requires a lot of imagination and creativity. - İyi bir hikaye yazmak çok fazla hayal gücü ve yaratıcılık gerektirir.",
  "cultural": "The city is famous for its historical and cultural heritage. - Şehir, tarihi ve kültürel mirasıyla ünlüdür.",
  "development": "Healthy food is essential for the physical development of children. - Sağlıklı yiyecekler çocukların fiziksel gelişimi için gereklidir.",
  "musical": "He showed a great musical talent from a very young age. - Çok genç yaşlardan itibaren harika bir müzikal yetenek gösterdi.",
  "musician": "The famous musician performed perfectly in front of thousands of fans. - Ünlü müzisyen binlerce hayranının önünde mükemmel bir performans sergiledi.",
  "organised": "She is very organised and always keeps her desk perfectly clean. - O çok organizedir ve masasını her zaman mükemmel temiz tutar.",
  "organiser": "The event organiser made sure everything went smoothly. - Etkinlik organizatörü her şeyin sorunsuz gitmesini sağladı.",
  "organize": "We need to organize a surprise party for her birthday. - Onun doğum günü için sürpriz bir parti organize etmeliyiz.",
  "performer": "The street performer amazed the crowd with his magic tricks. - Sokak sanatçısı sihir numaralarıyla kalabalığı şaşkına çevirdi.",
  "perform": "The choir will perform classical songs at the winter concert. - Koro kış konserinde klasik şarkılar performans sergileyecek.",
  "wait a second": "Please wait a second, I need to find my keys. - Lütfen bir saniye bekle, anahtarlarımı bulmam lazım.",
  "one moment please": "One moment please, I will connect you to the manager. - Bir an lütfen, sizi yöneticiye bağlayacağım.",
  "let me check for you": "Let me check for you if we have that shirt in your size. - O gömleğin bedeninize uygun olanı var mı, sizin için kontrol edeyim.",
  "misses": "If he misses the train, he will be late for the meeting. - Treni ıskalarsa, toplantıya geç kalacak.",
  "referee": "The referee blew the whistle to start the football match. - Hakem futbol maçını başlatmak için düdük çaldı.",
  "afraid of": "My little brother is very afraid of the dark. - Küçük kardeşim karanlıktan çok korkar.",
  "scared of": "She was too scared of heights to look down from the balcony. - Balkondan aşağı bakamayacak kadar yükseklikten korkmuştu.",
  "essential for": "Water is absolutely essential for the survival of all living things. - Su, tüm canlıların hayatta kalması için kesinlikle gereklidir.",
  "nervous": "I always feel nervous before speaking in front of a large crowd. - Büyük bir kalabalığın önünde konuşmadan önce her zaman gergin hissederim.",
  "tired of": "I am so tired of doing the same boring tasks every single day. - Her gün aynı sıkıcı görevleri yapmaktan çok bıktım.",
  "right for": "You need to decide if this career path is really right for you. - Bu kariyer yolunun senin için gerçekten doğru olup olmadığına karar vermelisin.",
  "similar to": "Your new phone looks very similar to the one I bought last year. - Yeni telefonun geçen yıl aldığım telefona çok benzer görünüyor.",
  "popular with": "The new teacher is extremely popular with all the students. - Yeni öğretmen tüm öğrencilerle son derece popüler.",
  "perfect to": "This sunny weather is perfect to go for a long walk in the park. - Bu güneşli hava parkta uzun bir yürüyüşe çıkmak için mükemmel.",
  "definitely": "I will definitely call you when I get home tonight. - Bu gece eve vardığımda seni kesinlikle arayacağım.",
  "speaking of": "Speaking of movies, did you watch the new sci-fi film yet? - Filmlerden demişken, yeni bilim kurgu filmini izledin mi?",
  "that reminds me": "That reminds me, I need to buy some milk on the way back. - O bana şunu hatırlattı, dönüş yolunda biraz süt almam lazım.",
  "by the way": "By the way, what time does the concert start tonight? - Bu arada, bu gece konser saat kaçta başlıyor?",
  "I was saying": "As I was saying before we were interrupted, the project is almost done. - Bölünmeden önce diyordum ki, proje neredeyse bitti.",
  "identify": "It is important to identify the problem before trying to solve it. - Çözmeye çalışmadan önce sorunu belirlemek önemlidir.",
  "disappear": "The magician made the coin disappear in front of our eyes. - Sihirbaz gözlerimizin önünde madeni parayı kaybolmak (yok etmek) suretiyle büyüledi.",
  "value": "This antique vase has a very high historical value. - Bu antika vazonun çok yüksek tarihi bir değeri var.",
  "hurt": "Be careful with that knife, you might hurt yourself. - O bıçakla dikkatli ol, kendini incitirsin.",
  "adopted": "They decided to adopt a beautiful rescue dog from the shelter. - Barınaktan güzel bir kurtarma köpeği evlat edinmeye karar verdiler.",
  "honour": "It is a great honour to receive this prestigious award today. - Bugün bu prestijli ödülü almak büyük bir onur.",
  "retirement": "He is planning to travel the world after his retirement next year. - Gelecek yılki emekliliğinden sonra dünyayı gezmeyi planlıyor.",
  "thick": "You should wear a thick coat because it is freezing outside. - Dışarısı dondurucu soğuk olduğu için kalın bir kaban giymelisin.",
  "constantly": "The baby was crying constantly throughout the entire flight. - Bebek tüm uçuş boyunca sürekli ağlıyordu.",
  "reached": "We finally reached the top of the mountain after hours of climbing. - Saatler süren tırmanışın ardından nihayet dağın zirvesine ulaştık.",
  "negotiate": "They had to negotiate a better deal with the suppliers. - Tedarikçilerle daha iyi bir anlaşmayı müzakere etmek zorundaydılar.",
  "pressure": "She performs very well even under extreme pressure at work. - İş yerinde aşırı baskı altındayken bile çok iyi performans sergiler.",
  "ambitious": "He is an ambitious young lawyer who wants to become a partner soon. - Yakında ortak olmak isteyen hırslı genç bir avukattır.",
  "anxious": "I always feel anxious waiting for my exam results to be announced. - Sınav sonuçlarımın açıklanmasını beklerken her zaman endişeli hissederim.",
  "misjudged": "I completely misjudged his character; he is actually a very nice guy. - Karakterini tamamen yanlış yargılamışım; aslında çok iyi bir adam.",
  "smoother": "Using this special lotion makes your skin feel much smoother. - Bu özel losyonu kullanmak cildinizin çok daha pürüzsüz hissetmesini sağlar.",
  "nowadays": "Nowadays, teenagers spend too much time on their mobile phones. - Bugünlerde gençler cep telefonlarında çok fazla zaman harcıyorlar.",
  "presence": "Her calm presence in the room helped everyone relax. - Odadaki sakin varlığı herkesin rahatlamasına yardımcı oldu.",
  "avoid": "You should try to avoid eating too much sugar for a healthy diet. - Sağlıklı bir diyet için çok fazla şeker yemekten kaçınmaya çalışmalısın.",
  "adapted": "The popular novel was successfully adapted into an award-winning movie. - Popüler roman başarılı bir şekilde ödüllü bir filme uyarlandı.",
  "award": "She won the first prize award for her excellent science project. - Mükemmel bilim projesi için birincilik ödülünü kazandı.",
  "mess with": "You shouldn't mess with the wiring if you don't know what you are doing. - Ne yaptığını bilmiyorsan kablolarla bulaşmamalısın.",
  "miss": "I really miss the traditional food my grandmother used to make. - Büyükannemin eskiden yaptığı geleneksel yemekleri gerçekten özlüyorum.",
  "thin": "The ice on the lake is too thin to walk on safely. - Göldeki buz güvenle yürümek için çok ince.",
  "closed": "The library is closed on Sundays and public holidays. - Kütüphane pazar günleri ve resmi tatillerde kapalıdır.",
  "shelves": "We need to put up some new shelves to hold all these books. - Tüm bu kitapları koymak için bazı yeni raflar kurmalıyız.",
  "rebellious": "As a teenager, he had a very rebellious attitude towards authority. - Bir genç olarak, otoriteye karşı çok asi bir tutumu vardı.",
  "relaxed": "He looked completely relaxed while reading a book on the beach. - Sahilde kitap okurken tamamen rahat görünüyordu.",
  "therefore": "He was injured, and therefore he couldn't play in the final match. - O yaralıydı ve bu yüzden final maçında oynayamadı.",
  "provide": "The hotel will provide fresh towels and soap for all guests. - Otel tüm misafirler için taze havlu ve sabun sağlayacaktır.",
  "deal with": "She has to deal with angry customers every day at her job. - İşinde her gün kızgın müşterilerle ilgilenmek zorundadır.",
  "improve": "Practicing every day will help you improve your speaking skills. - Her gün pratik yapmak konuşma becerilerini iyileştirmene yardımcı olacaktır.",
  "make a good impression": "It is important to dress nicely to make a good impression at the interview. - Görüşmede iyi bir izlenim bırakmak için güzel giyinmek önemlidir.",
  "to be turned into": "The old factory is going to be turned into a modern art museum. - Eski fabrika modern bir sanat müzesine dönüştürülecek.",
  "take it back": "If the shirt doesn't fit, you can take it back to the store. - Eğer gömlek uymazsa, onu mağazaya geri götürebilirsin.",
  "turn it off and on again": "When my computer freezes, I usually just turn it off and on again. - Bilgisayarım donduğunda, genelde sadece kapatıp tekrar açarım.",
  "claim on your insurance": "If your car is stolen, you must make a claim on your insurance. - Eğer arabanız çalınırsa, sigortadan talep etmek zorundasınız.",
  "what have I got to lose": "I might as well apply for the job; what have I got to lose? - İşe başvursam iyi olur; kaybedecek neyim var ki?",
  "broken down": "My car has broken down twice this week on the highway. - Arabam bu hafta otoyolda iki kez bozuldu.",
  "spill": "Be careful not to spill hot coffee on your clean shirt. - Temiz gömleğine sıcak kahve dökmemeye dikkat et.",
  "annoying": "That loud noise coming from the street is really annoying. - Sokaktan gelen o yüksek ses gerçekten sinir bozucu.",
  "frozen screen": "I couldn't save my document because of the frozen screen. - Donmuş ekran yüzünden belgemi kaydedemedim.",
  "it turned out": "It turned out that we had been completely wrong all along. - Ortaya çıktı ki başından beri tamamen haksızmışız.",
  "coincidence": "Meeting you here in Paris is such a crazy coincidence! - Seninle burada Paris'te karşılaşmak ne çılgın bir tesadüf!",
  "in the end": "We tried our best, but in the end, it wasn't enough. - Elimizden gelenin en iyisini yaptık, ama sonunda yeterli olmadı.",
  "luckily": "Luckily, I found my lost wallet under the car seat. - Şans eseri, kayıp cüzdanımı araba koltuğunun altında buldum.",
  "straight away": "If you feel chest pain, you should see a doctor straight away. - Eğer göğüs ağrısı hissederseniz, derhal bir doktora görünmelisiniz.",
  "freecycling": "Freecycling is a great way to give away things you no longer need. - Bedava eşya takası, artık ihtiyacınız olmayan eşyaları vermenin harika bir yoludur.",
  "get a refund": "If the product is damaged, you have the right to get a refund. - Eğer ürün hasarlıysa, para iadesi alma hakkınız vardır.",
  "do you need a hand": "Those boxes look very heavy, do you need a hand carrying them? - O kutular çok ağır görünüyor, taşırken yardıma ihtiyacın var mı?",
  "ask a favour in return": "I will help you, but I might ask a favour in return someday. - Sana yardım edeceğim, ama bir gün karşılığında bir iyilik isteyebilirim.",
  "give someone a hand": "Can you give me a hand with this difficult math homework? - Bu zor matematik ödevinde bana yardım edebilir misin?",
  "take photos": "We stopped at the beautiful bridge to take photos of the sunset. - Gün batımının fotoğraf çekmek için o güzel köprüde durduk.",
  "give someone a lift": "It is raining heavily, let me give you a lift to the station. - Şiddetli yağmur yağıyor, seni arabayla istasyona bırakayım.",
  "talk through": "Let's sit down and talk through the problem before making a decision. - Karar vermeden önce oturup problemi enine boyuna tartışalım.",
  "for example": "You can eat many healthy foods, for example, apples and carrots. - Birçok sağlıklı yiyecek yiyebilirsiniz, örneğin, elma ve havuç.",
  "spread my wings": "Going to university abroad will allow me to spread my wings. - Yurtdışında üniversiteye gitmek kanatlarını açmama (yeni şeyler denememe) olanak tanıyacak.",
  "resigned": "The manager resigned from his position after the scandal was revealed. - Yönetici skandal ortaya çıktıktan sonra görevinden istifa etti.",
  "bored in my job": "I feel so bored in my job because every day is exactly the same. - İşimden sıkıldım çünkü her gün tamamen aynı.",
  "ask for recommendations": "We should ask for recommendations from the locals for a good restaurant. - İyi bir restoran için yerel halktan tavsiye istemeliyiz.",
  "worth asking": "I don't think he will agree, but it is still worth asking. - Kabul edeceğini sanmıyorum ama yine de sormaya değer.",
  "huge diamond": "The thief managed to steal the huge diamond from the museum display. - Hırsız müze vitrinindeki kocaman elması çalmayı başardı.",
  "ridiculous": "It is absolutely ridiculous to pay that much money for a plain t-shirt. - Düz bir tişört için o kadar para ödemek kesinlikle gülünç.",
  "take presents": "It is polite to take presents when you are invited to someone's house. - Birinin evine davet edildiğinde hediye götürmek kibarlıktır.",
  "arrive on time": "Please make sure to arrive on time for your dentist appointment. - Lütfen dişçi randevunuza zamanında varmaya özen gösterin.",
  "take your shoes off": "In our culture, you must take your shoes off before entering the house. - Kültürümüzde, eve girmeden önce ayakkabılarını çıkarmalısın.",
  "is there anything we can do to help": "We heard the bad news; is there anything we can do to help? - Kötü haberi duyduk; yardım edebileceğimiz bir şey var mı?",
  "is it OK if I": "Is it OK if I leave the office early today to see my doctor? - Bugün doktorumu görmek için ofisten erken çıksam sorun olur mu?",
  "do you mind if I": "Do you mind if I open the window to get some fresh air? - Biraz temiz hava almak için pencereyi açsam sakıncası var mı?",
  "not at all": "Do you mind if I sit here? - Not at all, please go ahead. - Buraya oturmamın sakıncası var mı? - Hiç de bile, lütfen buyrun.",
  "that must be exciting": "You are traveling to Japan? Wow, that must be exciting! - Japonya'ya mı seyahat ediyorsun? Vay canına, bu heyecan verici olmalı!",
  "action shots": "The sports photographer took incredible action shots during the final match. - Spor fotoğrafçısı final maçı sırasında inanılmaz hareketli çekimler yaptı.",
  "generally": "Generally, it is warmer in the south than in the north. - Genellikle güney, kuzeyden daha sıcaktır.",
  "normally": "I normally wake up at 7 AM, but today I slept until 9 AM. - Normalde sabah 7'de uyanırım ama bugün 9'a kadar uyudum.",
  "typically": "Typically, a British breakfast includes eggs, bacon, and beans. - Tipik olarak, bir İngiliz kahvaltısı yumurta, pastırma ve fasulye içerir.",
  "as a rule": "As a rule, you should not eat heavily right before going to bed. - Genel kural olarak, yatmadan hemen önce ağır yememelisiniz.",
  "a couple of": "I just need a couple of minutes to finish typing this email. - Bu e-postayı yazmayı bitirmek için birkaç dakikaya ihtiyacım var.",
  "sort of thing": "I enjoy hiking, camping, and that sort of thing. - Doğa yürüyüşü, kamp ve o tarz şeylerden hoşlanırım.",
  "kind of thing": "Action movies aren't really my kind of thing. - Aksiyon filmleri pek benim tarzım bir şey değil.",
  "vague language": "Politicians often use vague language to avoid answering direct questions. - Politikacılar doğrudan soruları yanıtlamaktan kaçınmak için genellikle belirsiz dil kullanırlar.",
  "except for": "Everyone attended the meeting except for John, who was sick. - Hasta olan John haricinde herkes toplantıya katıldı.",
  "highly recommended": "This book is highly recommended for anyone interested in history. - Bu kitap tarihle ilgilenen herkes için şiddetle tavsiye edilir.",
  "I doubt": "I doubt that they will arrive on time in this heavy traffic. - Bu yoğun trafikte zamanında varacaklarından şüpheliyim.",
  "just a moment": "Could you wait just a moment while I find your file? - Dosyanızı bulurken sadece bir saniye bekler misiniz?",
  "let me check": "Let me check the schedule to see if the doctor is available. - Doktorun müsait olup olmadığını görmek için programı kontrol edeyim.",
  "public speaking": "Many people have a deep fear of public speaking. - Birçok insanın topluluk önünde konuşma konusunda derin bir korkusu vardır.",
  "what if she says no": "I want to ask her to the party, but what if she says no? - Onu partiye davet etmek istiyorum, ama ya hayır derse?",
  "as I was saying": "As I was saying before the phone rang, we need to finish this report. - Telefon çalmadan önce dediğim gibi, bu raporu bitirmemiz gerekiyor.",
  "changing the subject": "Anyway, changing the subject completely, what are you doing this weekend? - Her neyse, konuyu tamamen değiştirirsek, bu hafta sonu ne yapıyorsun?"
};

let content = fs.readFileSync('./src/data/vocabularyData.ts', 'utf8');

for (const [word, example] of Object.entries(examples)) {
  const regex = new RegExp(`(word:\\s*'${word.replace(/[.*+?^$\{\}()|[\\]\\\\]/g, '\\$&')}',\\s*translation:\\s*'[^']+',\\s*example:\\s*)''`, 'g');
  content = content.replace(regex, `$1'${example.replace(/'/g, "\\'")}'`);
}

fs.writeFileSync('./src/data/vocabularyData.ts', content);
console.log('Successfully updated vocabulary examples!');
