const fs = require('fs');
const path = require('path');

const newVocab = [
    { word: 'successful', translation: 'Başarılı', category: 'adjective' },
    { word: 'talented', translation: 'Yetenekli', category: 'adjective' },
    { word: 'intelligent', translation: 'Zeki', category: 'adjective' },
    { word: 'confident', translation: 'Öz güvenli', category: 'adjective' },
    { word: 'determined', translation: 'Kararlı', category: 'adjective' },
    { word: 'achievement', translation: 'Başarı', category: 'noun' },
    { word: 'attitude', translation: 'Tutum', category: 'noun' },
    { word: 'give up', translation: 'Vazgeçmek', category: 'verb' },
    { word: 'sociable', translation: 'Sosyal', category: 'adjective' },
    { word: 'outgoing', translation: 'Dışa dönük, uyumlu', category: 'adjective' },
    { word: 'talkative', translation: 'Konuşkan', category: 'adjective' },
    { word: 'shy', translation: 'Utangaç', category: 'adjective' },
    { word: 'reserved', translation: 'Duygu belli etmeyen', category: 'adjective' },
    { word: 'lively', translation: 'Canlı', category: 'adjective' },
    { word: 'serious', translation: 'Ciddi', category: 'adjective' },
    { word: 'sensitive', translation: 'Hassas', category: 'adjective' },
    { word: 'valued', translation: 'Değerli', category: 'adjective' },
    { word: 'movement', translation: 'Eylem, hareket', category: 'noun' },
    { word: 'despite', translation: '-e rağmen', category: 'preposition' },
    { word: 'songwriters', translation: 'Söz yazarı', category: 'noun' },
    { word: 'bright', translation: 'Zeki, parlak', category: 'adjective' },
    { word: 'towards', translation: 'Karşı, -e doğru', category: 'preposition' },
    { word: 'ability', translation: 'Yetenek', category: 'noun' },
    { word: 'pick up', translation: 'Teslim almak, almak', category: 'verb' },
    { word: 'website', translation: 'Website', category: 'noun' },
    { word: 'isn\'t it', translation: 'Değil mi', category: 'phrase' },
    { word: 'don\'t you', translation: 'Değil mi', category: 'phrase' },
    { word: 'Do you need a hand?', translation: 'Yardıma ihtiyacın var mı?', category: 'phrase' },
    { word: 'Do you think you could?', translation: 'Acaba yapabilir misin diye', category: 'phrase' },
    { word: 'I wondered if you could', translation: 'Merak ettim, acaba yapabilir misin', category: 'phrase' },
    { word: 'Could I ask you a favor?', translation: 'Senden bir iyilik isteyebilir miyim?', category: 'phrase' },
    { word: 'What do you need?', translation: 'Neye ihtiyacın var?', category: 'phrase' },

    { word: 'pollution', translation: 'Kirlilik', category: 'noun' },
    { word: 'prevent', translation: 'Önlemek', category: 'verb' },
    { word: 'wildlife', translation: 'Vahşi yaşam', category: 'noun' },
    { word: 'endangered', translation: 'Nesli tehlikede olan', category: 'adjective' },
    { word: 'save', translation: 'Korumak', category: 'verb' },
    { word: 'damaged', translation: 'Zarar vermek', category: 'verb' },
    { word: 'protect', translation: 'Korumak', category: 'verb' },
    { word: 'climate change', translation: 'İklim değişimi', category: 'noun' },
    { word: 'environment', translation: 'Çevre', category: 'noun' },
    { word: 'recycle', translation: 'Geri dönüşüm', category: 'verb' },
    { word: 'creature', translation: 'Yaratık', category: 'noun' },
    { word: 'local', translation: 'Yerel', category: 'adjective' },
    { word: 'destroy', translation: 'Yerle bir etmek', category: 'verb' },
    { word: 'species', translation: 'Tür', category: 'noun' },
    { word: 'survive', translation: 'Hayatta kalmak', category: 'verb' },
    { word: 'limit', translation: 'Sınırlamak', category: 'verb' },
    { word: 'branch', translation: 'Dal', category: 'noun' },
    { word: 'petals', translation: 'Taç yaprak', category: 'noun' },
    { word: 'feathers', translation: 'Tüy', category: 'noun' },
    { word: 'scales', translation: 'Pul', category: 'noun' },
    { word: 'fur', translation: 'Kürk', category: 'noun' },
    { word: 'skin', translation: 'Deri', category: 'noun' },
    { word: 'leaf', translation: 'Yaprak', category: 'noun' },
    { word: 'tail', translation: 'Kuyruk', category: 'noun' },
    { word: 'paws', translation: 'Pati', category: 'noun' },
    { word: 'web', translation: 'Ağ', category: 'noun' },
    { word: 'bay', translation: 'Koy', category: 'noun' },
    { word: 'rainforest', translation: 'Yağmur ormanı', category: 'noun' },
    { word: 'waterfall', translation: 'Şelale', category: 'noun' },
    { word: 'cave', translation: 'Mağara', category: 'noun' },
    { word: 'coast', translation: 'Kıyı', category: 'noun' },
    { word: 'stream', translation: 'Akarsu', category: 'noun' },
    { word: 'desert', translation: 'Çöl', category: 'noun' },
    { word: 'valley', translation: 'Vadi', category: 'noun' },

    { word: 'hook', translation: 'Kanca', category: 'noun' },
    { word: 'sticking', translation: 'Yapışmak', category: 'verb' },
    { word: 'dry', translation: 'Kuru', category: 'adjective' },
    { word: 'gold fish', translation: 'Japon balığı', category: 'noun' },
    { word: 'handle', translation: 'Kulp', category: 'noun' },
    { word: 'inspire', translation: 'İlham almak', category: 'verb' },
    { word: 'seeds', translation: 'Tohum', category: 'noun' },
    { word: 'rose', translation: 'Gül', category: 'noun' },
    { word: 'pine tree', translation: 'Çam ağacı', category: 'noun' },

    { word: 'boarding pass', translation: 'Biniş kartı', category: 'noun' },
    { word: 'air conditioning', translation: 'Klima', category: 'noun' },
    { word: 'souvenir shop', translation: 'Hediyelik eşya dükkanı', category: 'noun' },
    { word: 'bottle opener', translation: 'Şişe açacağı', category: 'noun' },
    { word: 'window seat', translation: 'Cam kenarı', category: 'noun' },
    { word: 'dishwasher', translation: 'Bulaşık makinesi', category: 'noun' },
    { word: 'sight tour', translation: 'Gezi turu', category: 'noun' },
    { word: 'insect repellent', translation: 'Böcek savar', category: 'noun' },
    { word: 'sleeping bag', translation: 'Uyku tulumu', category: 'noun' },
    { word: 'street map', translation: 'Harita', category: 'noun' },
    { word: 'cooked', translation: 'Pişmiş', category: 'adjective' },
    { word: 'raw', translation: 'Çiğ', category: 'adjective' },
    { word: 'creamy', translation: 'Kremalı', category: 'adjective' },
    { word: 'sweet', translation: 'Tatlı', category: 'adjective' },
    { word: 'crunchy', translation: 'Kıtır kıtır', category: 'adjective' },
    { word: 'sour', translation: 'Ekşi', category: 'adjective' },
    { word: 'heavy', translation: 'Ağır', category: 'adjective' },
    { word: 'fresh', translation: 'Taze', category: 'adjective' },
    { word: 'light', translation: 'Hafif', category: 'adjective' },
    { word: 'dried', translation: 'Kurutulmuş', category: 'adjective' },
    { word: 'insights', translation: 'İç yüzünü anlamak', category: 'noun' },
    { word: 'integral', translation: 'Temel, önemli', category: 'adjective' },
    { word: 'approach to', translation: 'Yaklaşım', category: 'noun' },
    { word: 'at the heart of', translation: 'Kalbine', category: 'phrase' },
    { word: 'supplement', translation: 'Ek', category: 'noun' },
    { word: 'with authority', translation: 'Yetkili', category: 'phrase' },
    { word: 'augment', translation: 'Büyütmek', category: 'verb' },
    { word: 'vaccinations', translation: 'Aşı', category: 'noun' },
    { word: 'planter', translation: 'Saksı', category: 'noun' },
    { word: 'contribute', translation: 'Katkıda bulunmak', category: 'verb' },
    { word: 'herb', translation: 'Bitki', category: 'noun' },
    { word: 'mention', translation: 'Bahsetmek', category: 'verb' },
    { word: 'in advance', translation: 'Önceden', category: 'phrase' },
    { word: 'cuisine', translation: 'Mutfak kültürü', category: 'noun' },
    { word: 'steamed rice', translation: 'Buharda pilav', category: 'noun' },
    { word: 'peanut', translation: 'Fıstık', category: 'noun' },
    { word: 'randomly', translation: 'Rastgele', category: 'adverb' },
    { word: 'explore', translation: 'Keşfetmek', category: 'verb' },

    { word: 'propose', translation: 'Evlenme teklif etmek', category: 'verb' },
    { word: 'bride', translation: 'Gelin', category: 'noun' },
    { word: 'groom', translation: 'Damat', category: 'noun' },
    { word: 'jewellery', translation: 'Mücevher', category: 'noun' },
    { word: 'varied', translation: 'Çeşitli', category: 'adjective' },
    { word: 'flat', translation: 'Düz', category: 'adjective' },
    { word: 'What would you do?', translation: 'Ne yapardın?', category: 'phrase' },
    { word: 'It\'s worth asking?', translation: 'Sormaya değer mi?', category: 'phrase' },
    { word: 'You are kidding!', translation: 'Şaka yapıyorsun!', category: 'phrase' },
    { word: 'I don\'t believe it', translation: 'İnanmıyorum', category: 'phrase' },

    { word: 'moving house', translation: 'Ev taşımak', category: 'phrase' },
    { word: 'floor', translation: 'Kat', category: 'noun' },
    { word: 'neighbour', translation: 'Komşu', category: 'noun' },
    { word: 'move out of', translation: 'Bir yerden çıkmak, taşınmak', category: 'verb' },
    { word: 'attic', translation: 'Çatı katı', category: 'noun' },
    { word: 'basement', translation: 'Alt kat, bodrum', category: 'noun' },
    { word: 'terrace', translation: 'Teras', category: 'noun' },
    { word: 'renting', translation: 'Kiralamak', category: 'verb' },
    { word: 'block', translation: 'Apartman', category: 'noun' },
    { word: 'neighbourhood', translation: 'Mahalle', category: 'noun' },
    { word: 'ground floor', translation: 'Zemin kat', category: 'noun' },
    { word: 'landing', translation: 'Sahanlık', category: 'noun' },
    { word: 'step', translation: 'Basamak', category: 'noun' },
    { word: 'argue with', translation: 'Biriyle tartışmak', category: 'verb' },
    { word: 'cope with', translation: 'Bir şeyle başa çıkmak', category: 'verb' },
    { word: 'think about', translation: 'Bir şeyi düşünmek', category: 'verb' },
    { word: 'care about', translation: 'Bir şeyi umursamak', category: 'verb' },
    { word: 'worry about', translation: 'Bir şey için endişelenmek', category: 'verb' },
    { word: 'complain about', translation: 'Bir şey hakkında şikayet etmek', category: 'verb' },
    { word: 'rely on', translation: 'Güvenmek', category: 'verb' },
    { word: 'depend on', translation: 'Bağlı olmak', category: 'verb' },
    { word: 'pay for', translation: 'Ücretini ödemek', category: 'verb' },
    { word: 'wait for', translation: 'Beklemek', category: 'verb' },
    { word: 'apologise for', translation: 'Özür dilemek', category: 'verb' },
    { word: 'believe in', translation: 'İnanmak', category: 'verb' },
    { word: 'succeed in', translation: 'Başarmak', category: 'verb' },
    { word: 'belong to', translation: 'Ait olmak', category: 'verb' },
    { word: 'apologise to', translation: 'Birinden özür dilemek', category: 'verb' },
    { word: 'complain to', translation: 'Birine şikayet etmek', category: 'verb' },

    { word: 'deduction', translation: 'Çıkarımda bulunmak', category: 'noun' },
    { word: 'outskirts', translation: 'Şehrin etekleri', category: 'noun' },
    { word: 'entire', translation: 'Tamamı', category: 'adjective' },
    { word: 'accommodation', translation: 'Konaklama', category: 'noun' },
    { word: 'pleasure', translation: 'Zevk', category: 'noun' },
    { word: 'property', translation: 'Mal/mülk', category: 'noun' },
    { word: 'range', translation: 'Aralık', category: 'noun' },
    { word: 'hosts', translation: 'Ev sahipleri', category: 'noun' },
    { word: 'nearby', translation: 'Yakınlarda', category: 'adjective' },
    { word: 'theft', translation: 'Hırsızlık', category: 'noun' },
    { word: 'cottage', translation: 'Kulübe', category: 'noun' },
    { word: 'Is it ok if I... ?', translation: '... yapsam olur mu?', category: 'phrase' },
    { word: 'Is there anything... ?', translation: 'Herhangi bir şey var mı?', category: 'phrase' },

    { word: 'brainstorm', translation: 'Beyin fırtınası yapmak', category: 'verb' },
    { word: 'create', translation: 'Yaratmak', category: 'verb' },
    { word: 'hold a meeting', translation: 'Toplantı yapmak', category: 'verb' },
    { word: 'subscribe', translation: 'Abone olmak', category: 'verb' },
    { word: 'series', translation: 'Dizi', category: 'noun' },
    { word: 'episode', translation: 'Bölüm', category: 'noun' },
    { word: 'deliver', translation: 'Teslim etmek', category: 'verb' },
    { word: 'put up', translation: 'Asmak', category: 'verb' },
    { word: 'post on', translation: 'Gönderi paylaşmak', category: 'verb' },
    { word: 'newsfeed', translation: 'Akış', category: 'noun' },
    { word: 'items', translation: 'Öğe, madde', category: 'noun' },
    { word: 'update', translation: 'Güncellemek', category: 'verb' },
    { word: 'advise', translation: 'Tavsiye etmek', category: 'verb' },
    { word: 'ask', translation: 'Rica etmek, sormak', category: 'verb' },
    { word: 'offer', translation: 'Teklif yapmak', category: 'verb' },
    { word: 'persuade', translation: 'İkna etmek', category: 'verb' },
    { word: 'promise', translation: 'Söz vermek', category: 'verb' },
    { word: 'recommend', translation: 'Tavsiye etmek', category: 'verb' },
    { word: 'threaten', translation: 'Tehdit etmek', category: 'verb' },
    { word: 'warn', translation: 'Uyarmak', category: 'verb' },
    { word: 'agree', translation: 'Aynı fikirde olmak', category: 'verb' },
    { word: 'refuse', translation: 'Reddetmek', category: 'verb' },

    { word: 'basis', translation: 'Temel, baz', category: 'noun' },
    { word: 'come across', translation: 'Karşılaşmak', category: 'verb' },
    { word: 'fooled', translation: 'Kandırılmış', category: 'adjective' },
    { word: 'genuine', translation: 'Gerçek', category: 'adjective' },
    { word: 'kept', translation: 'Tutmak, sürmek', category: 'verb' },
    { word: 'made up', translation: 'Uydurmak', category: 'verb' },
    { word: 'submitted', translation: 'Teslim etmek', category: 'verb' },
    { word: 'setting up', translation: 'Kurmak', category: 'verb' },
    { word: 'attend', translation: 'Katılmak', category: 'verb' },
    { word: 'get through', translation: 'Başarmak, bağlanmak', category: 'verb' },
    { word: 'according to', translation: '-e göre', category: 'phrase' },
    { word: 'wished', translation: 'Dilemek', category: 'verb' },
    { word: 'exist', translation: 'Var olmak', category: 'verb' },
    { word: 'enquiries', translation: 'Soru sormak, soruşturma', category: 'noun' },
    { word: 'pretending', translation: '-mış gibi yapmak', category: 'verb' },
    { word: 'deceive', translation: 'Aldatmak', category: 'verb' },
    { word: 'believe to', translation: 'İnanmak', category: 'verb' },
    { word: 'on the whole', translation: 'Tümüyle', category: 'phrase' },
    { word: 'stuff like that', translation: 'Öyle bir şeyler', category: 'phrase' },
    { word: 'with that kind of things', translation: 'Böyle şeyler', category: 'phrase' },
    { word: 'tends to', translation: 'Eğiliminde olmak', category: 'verb' },
    { word: 'a few', translation: 'Birkaç', category: 'adjective' },

    { word: 'disappointed', translation: 'Hayal kırıklığına uğramış', category: 'adjective' },
    { word: 'disappointing', translation: 'Hayal kırıklığına uğratan', category: 'adjective' },
    { word: 'amused', translation: 'Eğlenmiş', category: 'adjective' },
    { word: 'amusing', translation: 'Eğlenceli', category: 'adjective' },
    { word: 'depressed', translation: 'Depresif', category: 'adjective' },
    { word: 'depressing', translation: 'Depresif yapan', category: 'adjective' },
    { word: 'audience', translation: 'Dinleyici', category: 'noun' },
    { word: 'track', translation: 'Parça', category: 'noun' },
    { word: 'character', translation: 'Karakter', category: 'noun' },
    { word: 'event', translation: 'Etkinlik', category: 'noun' },
    { word: 'held', translation: 'Düzenlenmek', category: 'verb' },
    { word: 'gulf', translation: 'Körfez', category: 'noun' },
    { word: 'stage', translation: 'Sahne', category: 'noun' },
    { word: 'profits', translation: 'Kar', category: 'noun' },
    { word: 'charity', translation: 'Bağış', category: 'noun' },
    { word: 'beautiful', translation: 'Güzel', category: 'adjective' },
    { word: 'beauty', translation: 'Güzellik', category: 'noun' },
    { word: 'celebration', translation: 'Kutlama', category: 'noun' },
    { word: 'celebrate', translation: 'Kutlamak', category: 'verb' },
    { word: 'charitable', translation: 'Yardımsever', category: 'adjective' },
    { word: 'creative', translation: 'Yaratıcı', category: 'adjective' },
    { word: 'creativity', translation: 'Yaratıcılık', category: 'noun' },
    { word: 'cultural', translation: 'Kültürel', category: 'adjective' },
    { word: 'culture', translation: 'Kültür', category: 'noun' },
    { word: 'development', translation: 'Gelişim', category: 'noun' },
    { word: 'develop', translation: 'Gelişmek', category: 'verb' },
    { word: 'musical', translation: 'Müzikal', category: 'adjective' },
    { word: 'musician', translation: 'Müzisyen', category: 'noun' },
    { word: 'organised', translation: 'Düzenli', category: 'adjective' },
    { word: 'organiser', translation: 'Organizatör', category: 'noun' },
    { word: 'organise', translation: 'Düzenlemek', category: 'verb' },
    { word: 'performer', translation: 'Performans sergileyen', category: 'noun' },
    { word: 'perform', translation: 'Performans sergilemek', category: 'verb' },
    { word: 'wait a second', translation: 'Bir saniye bekle', category: 'phrase' },
    { word: 'one moment please', translation: 'Lütfen bir dakika', category: 'phrase' },
    { word: 'hang on', translation: 'Hatta kal, bekle', category: 'phrase' },
    { word: 'let me check for you', translation: 'Senin için kontrol edeyim', category: 'phrase' },

    { word: 'misses', translation: 'Iskalamak', category: 'verb' },
    { word: 'court', translation: 'Kort', category: 'noun' },
    { word: 'opponents', translation: 'Rakipler', category: 'noun' },
    { word: 'track', translation: 'Pist', category: 'noun' },
    { word: 'competitor', translation: 'Yarışmacı', category: 'noun' },
    { word: 'net', translation: 'File', category: 'noun' },
    { word: 'referee', translation: 'Hakem', category: 'noun' },
    { word: 'beat', translation: 'Yenmek', category: 'verb' },
    { word: 'do your homework', translation: 'Ödevini yapmak', category: 'phrase' },
    { word: 'do research', translation: 'Araştırma yapmak', category: 'phrase' },
    { word: 'do your best', translation: 'Elinden geleni yapmak', category: 'phrase' },
    { word: 'take a risk', translation: 'Risk almak', category: 'phrase' },
    { word: 'take a chance', translation: 'Şansını denemek', category: 'phrase' },
    { word: 'take advantage of something', translation: 'Bir şeyden faydalanmak', category: 'phrase' },
    { word: 'take part in something', translation: 'Bir şeye katılmak', category: 'phrase' },
    { word: 'take action', translation: 'Harekete geçmek', category: 'phrase' },
    { word: 'take care of someone', translation: 'Biriyle ilgilenmek', category: 'phrase' },
    { word: 'make money', translation: 'Para kazanmak', category: 'phrase' },
    { word: 'make a decision', translation: 'Karar vermek', category: 'phrase' },
    { word: 'make a mistake', translation: 'Hata yapmak', category: 'phrase' },
    { word: 'make progress', translation: 'İlerleme kaydetmek', category: 'phrase' },
    { word: 'make sense', translation: 'Mantıklı olmak', category: 'phrase' },
    { word: 'make a difference', translation: 'Fark yaratmak', category: 'phrase' },
    { word: 'make the most of something', translation: 'Bir şeyden en iyi şekilde yararlanmak', category: 'phrase' },
    { word: 'make a phone call', translation: 'Telefon görüşmesi yapmak', category: 'phrase' },
    { word: 'make new friends easily', translation: 'Kolayca yeni arkadaşlar edinmek', category: 'phrase' },
    { word: 'serendipity', translation: 'Tevafuk, şans eseri bulma', category: 'noun' },
    { word: 'afraid of', translation: 'Korkmak', category: 'verb' },
    { word: 'scared of', translation: 'Korkmuş', category: 'adjective' },
    { word: 'proud of', translation: 'Gururlu', category: 'adjective' },
    { word: 'essential for', translation: 'Gerekli', category: 'adjective' },
    { word: 'nervous', translation: 'Gergin', category: 'adjective' },
    { word: 'tired of', translation: 'Bıkmış', category: 'adjective' },
    { word: 'right for', translation: 'İçin doğru', category: 'phrase' },
    { word: 'similar to', translation: 'Benzer', category: 'adjective' },
    { word: 'popular with', translation: 'İle popüler', category: 'phrase' },
    { word: 'perfect to', translation: 'İçin mükemmel', category: 'phrase' },
    { word: 'definitely', translation: 'Kesinlikle', category: 'adverb' },
    { word: 'speaking of', translation: '-den bahsetmişken', category: 'phrase' },
    { word: 'that reminds me', translation: 'Bu bana hatırlatıyor', category: 'phrase' },
    { word: 'you\'ve got nothing', translation: 'Hiçbir şeyin yok', category: 'phrase' },
    { word: 'by the way', translation: 'Bu arada', category: 'phrase' },
    { word: 'I was saying', translation: 'Diyordum ki', category: 'phrase' },
    { word: 'I\'m still worried', translation: 'Hala endişeliyim', category: 'phrase' },

    { word: 'lend to', translation: 'Ödünç vermek', category: 'verb' },
    { word: 'borrow from', translation: 'Ödünç almak', category: 'verb' },
    { word: 'take', translation: 'Almak', category: 'verb' },
    { word: 'bring', translation: 'Getirmek', category: 'verb' },
    { word: 'robbed', translation: 'Soyulmak', category: 'verb' },
    { word: 'stole', translation: 'Çalmak', category: 'verb' },
    { word: 'miss', translation: 'Kaçırmak', category: 'verb' },
    { word: 'lose', translation: 'Kaybetmek', category: 'verb' },
    { word: 'raise', translation: 'Kaldırmak', category: 'verb' },
    { word: 'rise', translation: 'Yükselmek', category: 'verb' },
    { word: 'currently', translation: 'Şu sıralar', category: 'adverb' },
    { word: 'actually', translation: 'Aslında', category: 'adverb' },

    { word: 'get', translation: 'Elde etmek', category: 'verb' },
    { word: 'identify', translation: 'Tanımlamak', category: 'verb' },
    { word: 'disappear', translation: 'Kaybolmak', category: 'verb' },
    { word: 'value', translation: 'Değer, kıymet', category: 'noun' },
    { word: 'hurt', translation: 'İncitmek', category: 'verb' },
    { word: 'adopted', translation: 'Evlat edinmek', category: 'verb' },
    { word: 'honour', translation: 'Onur', category: 'noun' },
    { word: 'retirement', translation: 'Emeklilik', category: 'noun' },
    { word: 'thick', translation: 'Kalın', category: 'adjective' },
    { word: 'constantly', translation: 'Sürekli', category: 'adverb' },
    { word: 'reached', translation: 'Ulaşmak', category: 'verb' },
    { word: 'negotiate', translation: 'Müzakere etmek', category: 'verb' },
    { word: 'pressure', translation: 'Baskı', category: 'noun' },
    { word: 'ambitious', translation: 'Hırslı', category: 'adjective' },
    { word: 'anxious', translation: 'Endişeli', category: 'adjective' },
    { word: 'frustration', translation: 'Hüsran', category: 'noun' },
    { word: 'reduce', translation: 'Azaltmak', category: 'verb' },
    { word: 'conflict', translation: 'Tartışma', category: 'noun' },
    { word: 'misjudged', translation: 'Yanlış yargılama', category: 'verb' },
    { word: 'smoother', translation: 'Pürüzsüz', category: 'adjective' },
    { word: 'clarifying', translation: 'Açıklığa kavuşturmak', category: 'verb' },
    { word: 'awareness', translation: 'Farkındalık, bilinç', category: 'noun' },
    { word: 'likeness', translation: 'Benzerlik', category: 'noun' },
    { word: 'nowadays', translation: 'Bu günlerde', category: 'adverb' },
    { word: 'presence', translation: 'Var olmak, varlık', category: 'noun' },
    { word: 'avoid', translation: 'Kaçınmak', category: 'verb' },
    { word: 'adapted', translation: 'Uyarlanmış', category: 'adjective' },
    { word: 'award', translation: 'Ödül', category: 'noun' },
    { word: 'mess with', translation: 'Bulaşmak', category: 'verb' },
    { word: 'close', translation: 'Yakın', category: 'adjective' },
    { word: 'shelves', translation: 'Raf', category: 'noun' },
    { word: 'flexibility', translation: 'Esneklik', category: 'noun' },
    { word: 'rebellious', translation: 'Asi', category: 'adjective' },
    { word: 'relaxed', translation: 'Rahat', category: 'adjective' },
    { word: 'unfamiliar', translation: 'Tanımadık', category: 'adjective' },
    { word: 'struggle', translation: 'Mücadele etmek', category: 'verb' },
    { word: 'appreciate', translation: 'Takdir etmek', category: 'verb' },
    { word: 'interaction', translation: 'Etkileşim', category: 'noun' },
    { word: 'overcome', translation: 'Üstesinden gelmek', category: 'verb' },
    { word: 'due to', translation: 'Yüzünden', category: 'phrase' },
    { word: 'therefore', translation: 'Bu yüzden', category: 'adverb' },
    { word: 'lead to', translation: 'Yol açmak', category: 'verb' },

    { word: 'issue', translation: 'Sorun', category: 'noun' },
    { word: 'approach', translation: 'Yaklaşım', category: 'noun' },
    { word: 'solve', translation: 'Çözmek', category: 'verb' },
    { word: 'provide', translation: 'Sağlamak', category: 'verb' },
    { word: 'tackle', translation: 'Mücadele etmek', category: 'verb' },
    { word: 'concern', translation: 'Endişe', category: 'noun' },
    { word: 'deal with', translation: 'İlgilenmek', category: 'verb' },
    { word: 'improve', translation: 'İyileştirmek', category: 'verb' },
    { word: 'promotion', translation: 'Terfi', category: 'noun' }
];

const vocabPath = path.join(__dirname, 'src/data/vocabularyData.ts');

let currentVocabContent = fs.readFileSync(vocabPath, 'utf8');

let match = currentVocabContent.match(/export const vocabularyData: VocabularyWord\[\] = \[([\s\S]*?)\];/);

let insertedCount = 0;
let skippedCount = 0;

if (match) {
    let arrayContent = match[1];

    newVocab.forEach((v, index) => {
        // avoid duplicates
        const regex = new RegExp(`word:\\s*['"]${v.word.replace(/[.*+?^$\{\}()|[\]\\]/g, '\\$&')}['"]`, 'i');
        if (!regex.test(arrayContent)) {
            const newEntry = `
  {
    id: 'v-hw-u-new-${index + 1000}',
    word: '${v.word}',
    translation: '${v.translation}',
    example: '',
    category: '${v.category}',
  },`;
            arrayContent = arrayContent.replace(/\s*$/, newEntry + '\n');
            insertedCount++;
        } else {
            skippedCount++;
        }
    });

    const newFileContent = currentVocabContent.replace(/export const vocabularyData: VocabularyWord\\[\\] = \\[[\\s\\S]*?\\];/, "export const vocabularyData: VocabularyWord[] = [" + arrayContent + "];");
    fs.writeFileSync(vocabPath, newFileContent, 'utf8');
    
    console.log("Vocabulary Injection Complete: " + insertedCount + " added, " + skippedCount + " skipped.");
} else {
    console.log('Vocabulary array not found.');
}
