const fs = require('fs');

const examSets = `
  // ═══════════════════════════════════════════════════════════════
  // B LEVEL EXAM PRACTICE — MONTHLY 4
  // Part A: Cloze Test (Q1–15)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'blevel-m4-partA',
    title: 'B-Level Monthly 4 — Part A: Use of English',
    description: 'Circle the best option to complete the sentences. Texts about a mountain village and Seferihisar.',
    passage: \`After I finally reached the small mountain village, I was completely exhausted. I (1) __________ for nearly six hours before I saw a small café. When I (2) __________ the café, everyone inside looked at me in surprise. I must have looked terrible, but I was relieved because I had almost (3) __________ water and didn’t know how much longer I could continue. The small café reminded me of my childhood; when we visited villages like this, my grandfather and I (4) __________ sit for hours in places just like that, talking about life.

My own food had frozen in my backpack because of the cold. Fortunately, the café owner gave me a large bowl of hot soup, so I (5) __________ eat my own food. The soup was extremely hot, and my hands were still shaking from the cold. I tried (6) __________ the bowl steady, but my hands wouldn’t stop trembling. I finally stopped (7) __________ around for a moment to let the soup cool down before taking the first spoonful. I was lucky to find that place; otherwise, I would have frozen.

Since that day, I (8) __________ my hiking trips more carefully, and I feel much more confident now. I’ve even decided to take professional training, and by this time next year, I (9) __________ a certified survival course. With all this preparation, I’m sure that this time next year, I (10) __________ through the mountains again — but with much more confidence and experience.

Seferihisar, a small town near İzmir, became Turkey's first Cittaslow — a member of the international slow city movement — in 2009. Life there moves at (11) __________ a relaxed pace that many urban residents find refreshing. The locals take their time; they grow their own food, they (12) __________ their houses repaired using traditional methods, and they rarely feel rushed. It is a place (13) __________ community values have been carefully preserved over the generations. (14) __________ you ever visited a Cittaslow town, you would understand why so many people are now questioning the relentless pace of modern city life. Seferihisar (15) __________ had a similar character long before it officially joined the network; the evidence of its deep-rooted slow-living culture was everywhere.\`,
    difficulty: 'medium',
    grammarFocus: 'Tenses, Phrasal Verbs, Modals, Relative Clauses',
    questions: [
      { id: 'blm4-q1', type: 'multiple_choice', question: 'Part A, Q1:', options: ['was walking', 'had been walking', 'have been walking', 'would walk'], correctAnswer: 1, explanation: 'Past Perfect Continuous for an action before another past action.', difficulty: 'medium', grammarFocus: 'Tenses' },
      { id: 'blm4-q2', type: 'multiple_choice', question: 'Part A, Q2:', options: ['was entering', 'had entered', 'entered', 'had been entering'], correctAnswer: 2, explanation: 'Past Simple for a completed action.', difficulty: 'easy', grammarFocus: 'Tenses' },
      { id: 'blm4-q3', type: 'multiple_choice', question: 'Part A, Q3:', options: ['run out of', 'fallen out with', 'got away with', 'looked down on'], correctAnswer: 0, explanation: 'run out of = to have nothing left.', difficulty: 'medium', grammarFocus: 'Phrasal Verbs' },
      { id: 'blm4-q4', type: 'multiple_choice', question: 'Part A, Q4:', options: ['were used to', 'would', 'got used to', 'were supposed to'], correctAnswer: 1, explanation: 'would + bare infinitive for past habits.', difficulty: 'medium', grammarFocus: 'Modals' },
      { id: 'blm4-q5', type: 'multiple_choice', question: 'Part A, Q5:', options: ["needn't", "wasn't allowed to", "couldn't", "didn't have to"], correctAnswer: 3, explanation: 'didn\\'t have to = it was not necessary.', difficulty: 'medium', grammarFocus: 'Modals' },
      { id: 'blm4-q6', type: 'multiple_choice', question: 'Part A, Q6:', options: ['to hold', 'holding', 'to holding', 'hold'], correctAnswer: 0, explanation: 'try + to infinitive = make an effort.', difficulty: 'medium', grammarFocus: 'Verb Patterns' },
      { id: 'blm4-q7', type: 'multiple_choice', question: 'Part A, Q7:', options: ['looking', 'to looking', 'to look', 'look'], correctAnswer: 2, explanation: 'stop + to infinitive = stop an action to do something else.', difficulty: 'medium', grammarFocus: 'Verb Patterns' },
      { id: 'blm4-q8', type: 'multiple_choice', question: 'Part A, Q8:', options: ['planned', 'am planning', 'was planning', 'have been planning'], correctAnswer: 3, explanation: 'Present Perfect Continuous for an action starting in the past and continuing until now (Since that day).', difficulty: 'medium', grammarFocus: 'Tenses' },
      { id: 'blm4-q9', type: 'multiple_choice', question: 'Part A, Q9:', options: ['will complete', 'am completing', 'will be completing', 'will have completed'], correctAnswer: 3, explanation: 'Future Perfect for an action completed by a certain time in the future.', difficulty: 'medium', grammarFocus: 'Tenses' },
      { id: 'blm4-q10', type: 'multiple_choice', question: 'Part A, Q10:', options: ['will be hiking', 'will have hiked', 'will hike', 'am hiking'], correctAnswer: 0, explanation: 'Future Continuous for an action in progress at a certain time in the future.', difficulty: 'medium', grammarFocus: 'Tenses' },
      { id: 'blm4-q11', type: 'multiple_choice', question: 'Part A, Q11:', options: ['so', 'such', 'too', 'enough'], correctAnswer: 1, explanation: 'such a + adjective + noun.', difficulty: 'easy', grammarFocus: 'Quantifiers' },
      { id: 'blm4-q12', type: 'multiple_choice', question: 'Part A, Q12:', options: ['own', 'sell', 'have', 'invest'], correctAnswer: 2, explanation: 'have something done (causative).', difficulty: 'medium', grammarFocus: 'Causative' },
      { id: 'blm4-q13', type: 'multiple_choice', question: 'Part A, Q13:', options: ['which', 'who', 'where', 'when'], correctAnswer: 2, explanation: 'Relative pronoun for place.', difficulty: 'easy', grammarFocus: 'Relative Clauses' },
      { id: 'blm4-q14', type: 'multiple_choice', question: 'Part A, Q14:', options: ['if', 'unless', 'when', 'provided'], correctAnswer: 0, explanation: 'Second conditional (If you visited... you would).', difficulty: 'medium', grammarFocus: 'Conditionals' },
      { id: 'blm4-q15', type: 'multiple_choice', question: 'Part A, Q15:', options: ['must have', 'should have', 'can not have', 'might not have'], correctAnswer: 0, explanation: 'must have + V3 for strong deduction in the past.', difficulty: 'medium', grammarFocus: 'Modals' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Part B, C, D: Vocabulary & Grammar (Q16–29)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'blevel-m4-partBCD',
    title: 'B-Level Monthly 4 — Part B, C, D: Grammar & Vocabulary',
    description: 'Sentence transformation, completion, and word formation exercises.',
    difficulty: 'medium',
    grammarFocus: 'Restatement, Word Formation, Conditionals',
    questions: [
      { id: 'blm4-q16', type: 'multiple_choice', question: 'Q16: I was nervous before the presentation, but once I started, I felt much more confident.', options: ['Despite feeling very confident before the presentation, I became nervous as soon as I started.', 'Although I was nervous before the presentation, I felt much more confident after I started.', 'I was not nervous at all before the presentation, so I delivered it confidently from the beginning.', 'In spite of feeling confident before starting, I struggled to continue the presentation.'], correctAnswer: 1, explanation: 'Sentence restatement.', difficulty: 'medium', grammarFocus: 'Restatement' },
      { id: 'blm4-q17', type: 'multiple_choice', question: 'Q17: It was a mistake for Anna not to call the police immediately.', options: ['Anna must have called the police immediately after the incident.', 'Anna wishes she had called the police immediately.', 'Anna should have called the police immediately.', 'Anna can\\'t have called the police immediately.'], correctAnswer: 2, explanation: 'should have + V3 for past regret/mistake.', difficulty: 'medium', grammarFocus: 'Modals' },
      { id: 'blm4-q18', type: 'multiple_choice', question: 'Q18: We asked a professional company to clean the windows after the storm.', options: ['We had the windows cleaned after the storm by a professional company.', 'We cleaned the windows ourselves after the storm.', 'The windows were cleaning by a professional company after the storm.', 'The storm cleaned the windows; we did not need a professional company.'], correctAnswer: 0, explanation: 'Causative structure: have something done.', difficulty: 'medium', grammarFocus: 'Causative' },
      { id: 'blm4-q19', type: 'multiple_choice', question: 'Q19: If the athlete had not been caught using illegal substances, he would not have been banned for two years.', options: ['The athlete is banned now because he uses illegal substances.', 'The athlete was banned even though he had not been caught using illegal substances.', 'The athlete was banned for two years because he had used illegal substances.', 'The athlete was banned for two years because he was caught using illegal substances.'], correctAnswer: 3, explanation: 'Third conditional restatement.', difficulty: 'medium', grammarFocus: 'Conditionals' },
      { id: 'blm4-q20', type: 'multiple_choice', question: 'Q20: He had not revised the topics thoroughly before the exam; as a result, his performance was much weaker than expected.', options: ['His performance was below expectations as he had not revised the topics in detail before the exam.', 'Although he had studied thoroughly, he did not expect the exam to be this difficult.', 'He didn\\'t perform well in the exam even though he had studied all the topics.', 'Because his performance was worse than he had expected, he decided to revise the topics.'], correctAnswer: 0, explanation: 'Cause and effect restatement.', difficulty: 'medium', grammarFocus: 'Restatement' },
      { id: 'blm4-q21', type: 'multiple_choice', question: 'Q21: If the government had responded to public concerns earlier, __________.', options: ['people will trust the authorities more', 'people would have trusted the authorities more', 'people trust the authorities more', 'people had trusted the authorities more'], correctAnswer: 1, explanation: 'Third conditional result clause: would have + V3.', difficulty: 'medium', grammarFocus: 'Conditionals' },
      { id: 'blm4-q22', type: 'multiple_choice', question: 'Q22: By the time the results are announced tomorrow, __________.', options: ['the committee will have reviewed all the applications', 'the committee reviews all the applications', 'the committee is reviewing all the applications', 'the committee will review all the applications'], correctAnswer: 0, explanation: 'Future Perfect (will have + V3) with by the time.', difficulty: 'medium', grammarFocus: 'Tenses' },
      { id: 'blm4-q23', type: 'multiple_choice', question: 'Q23: __________, many countries have made significant progress in protecting women\\'s rights.', options: ['Gender equality is not achieved; therefore', 'Because gender equality is partly achieved', 'Although gender equality is still not fully achieved', 'Despite gender equality laws against gender discrimination'], correctAnswer: 2, explanation: 'Contrast linkers (Although).', difficulty: 'medium', grammarFocus: 'Conjunctions' },
      { id: 'blm4-q24', type: 'multiple_choice', question: 'Q24: The "Animal Protection Act", __________, has led to stricter penalties for animal abuse.', options: ['who was introduced in 2019', 'which introduced in 2019', 'that was introduced in 2019', 'which was introduced in 2019'], correctAnswer: 3, explanation: 'Non-defining relative clause requires "which" + passive.', difficulty: 'medium', grammarFocus: 'Relative Clauses' },
      { id: 'blm4-q25', type: 'multiple_choice', question: 'Q25: It was the lack of financial support __________. ', options: ['that made many university students struggle to continue their education', 'which many university students struggle to continue their education', 'that many university students are struggling to continue their education', 'what made many university students struggle to continue their education'], correctAnswer: 0, explanation: 'Cleft sentence: It was X that...', difficulty: 'medium', grammarFocus: 'Cleft Sentences' },
      { id: 'blm4-q26', type: 'multiple_choice', question: 'Q26: The police arrested the man responsible for the ___ of a local businessman last month.', options: ['kidnapping', 'kidnapper', 'kidnapped', 'kidnap'], correctAnswer: 0, explanation: 'Noun form needed (gerund/noun).', difficulty: 'medium', grammarFocus: 'Word Formation' },
      { id: 'blm4-q27', type: 'multiple_choice', question: 'Q27: The security guard caught a ___ trying to hide two jackets under his coat.', options: ['shoplifter', 'shoplifting', 'shoplifted', 'shoplift'], correctAnswer: 0, explanation: 'Noun for a person who steals from a shop.', difficulty: 'easy', grammarFocus: 'Word Formation' },
      { id: 'blm4-q28', type: 'multiple_choice', question: 'Q28: Everyone in the office knew he was a compulsive ___, but no one had the courage to confront him.', options: ['lying', 'lie', 'liar', 'lied'], correctAnswer: 2, explanation: 'Noun for a person who lies.', difficulty: 'easy', grammarFocus: 'Word Formation' },
      { id: 'blm4-q29', type: 'multiple_choice', question: 'Q29: Students who are involved in long-term research projects are expected to be __________, as collecting and analyzing data often takes a significant amount of time and requires careful attention.', options: ['impatient', 'patient', 'patience', 'patiently'], correctAnswer: 1, explanation: 'Adjective required after "be".', difficulty: 'easy', grammarFocus: 'Word Formation' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Part E: Vocabulary Multiple Choice (Q30–40)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'blevel-m4-partE',
    title: 'B-Level Monthly 4 — Part E: Vocabulary',
    description: 'Choose the correct option to complete the sentences.',
    difficulty: 'medium',
    grammarFocus: 'Vocabulary, Phrasal Verbs',
    questions: [
      { id: 'blm4-q30', type: 'multiple_choice', question: 'Q30: The song became popular very quickly because it had a/an ______ that stayed in people\\'s minds.', options: ['accent', 'hook', 'scar', 'genre'], correctAnswer: 1, explanation: 'hook (a catchy part of a song).', difficulty: 'medium', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q31', type: 'multiple_choice', question: 'Q31: He told himself to ______ before speaking, so that he would not say something he regretted.', options: ['come up', 'cope with', 'calm down', 'pay off'], correctAnswer: 2, explanation: 'calm down (relax).', difficulty: 'easy', grammarFocus: 'Phrasal Verbs' },
      { id: 'blm4-q32', type: 'multiple_choice', question: 'Q32: The company decided to ______ unnecessary expenses to survive the economic crisis.', options: ['cut down on', 'take charge', 'settle down', 'break into'], correctAnswer: 0, explanation: 'cut down on (reduce).', difficulty: 'medium', grammarFocus: 'Phrasal Verbs' },
      { id: 'blm4-q33', type: 'multiple_choice', question: 'Q33: She was shocked by his ______ behavior, which no one could explain logically.', options: ['arranged', 'bizarre', 'sentimental', 'underrated'], correctAnswer: 1, explanation: 'bizarre (strange/unusual).', difficulty: 'medium', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q34', type: 'multiple_choice', question: 'Q34: He got into serious trouble after trying to ______ during the exam.', options: ['steal', 'strain', 'treat', 'cheat'], correctAnswer: 3, explanation: 'cheat (act dishonestly).', difficulty: 'easy', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q35', type: 'multiple_choice', question: 'Q35: The children decided to ______ from home after an argument, but they returned later.', options: ['erupt', 'run away', 'put aside', 'donate'], correctAnswer: 1, explanation: 'run away (leave secretly).', difficulty: 'easy', grammarFocus: 'Phrasal Verbs' },
      { id: 'blm4-q36', type: 'multiple_choice', question: 'Q36: Because of his student loans, he is still in ______ even though he has a full-time job.', options: ['interest rate', 'donations', 'debt', 'consciousness'], correctAnswer: 2, explanation: 'debt (money owed).', difficulty: 'easy', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q37', type: 'multiple_choice', question: 'Q37: The advertisement was simple but very ______, so people remembered it easily.', options: ['catchy', 'detached', 'sophisticated', 'imaginary'], correctAnswer: 0, explanation: 'catchy (memorable).', difficulty: 'easy', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q38', type: 'multiple_choice', question: 'Q38: She found the background noise extremely ______ while trying to concentrate on her work.', options: ['innovative', 'irritating', 'patient', 'enchanted'], correctAnswer: 1, explanation: 'irritating (annoying).', difficulty: 'medium', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q39', type: 'multiple_choice', question: 'Q39: After working hard for years, he realized that being ______ was the key to success.', options: ['consistent', 'spectacular', 'dizzy', 'underrated'], correctAnswer: 0, explanation: 'consistent (acting in the same way over time).', difficulty: 'medium', grammarFocus: 'Vocabulary' },
      { id: 'blm4-q40', type: 'multiple_choice', question: 'Q40: In the museum, visitors can see ancient ______ that contain historical laws and religious texts written by hand.', options: ['refusal', 'scrolls', 'conservation', 'dimension'], correctAnswer: 1, explanation: 'scrolls (rolls of paper/parchment).', difficulty: 'medium', grammarFocus: 'Vocabulary' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Reading Exam Practice (Q41–55)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'blevel-m4-reading',
    title: 'B-Level Monthly 4 — Reading Practice',
    description: 'Read the texts carefully and choose the correct option in the questions below.',
    passage: \`TEXT I: The Woman Who Survived the Impossible
1 In January 2009, Andes Mountain guide Elena Vargas set off on a solo hiking expedition in southern Patagonia. Experienced and well-equipped, she carried a fragrant mix of dried herbs and high-protein rations in her pack, along with her emergency supplies. On the third day, a sudden blizzard struck without warning. Within hours, Elena was completely isolated from any trail, enclosed by walls of white with no visibility beyond a few metres. Her GPS device had failed, and temperatures plunged to minus thirty degrees Celsius.

2 What followed was a dramatic twenty-two-day survival story that would later captivate readers and researchers worldwide. Elena survived by constructing a snow shelter, using her knowledge of edible mountain plants, and maintaining a strict daily routine. She melted snow for water, foraged for roots, and even managed to start a small fire using materials from her pack. Despite the mild hope she clung to each morning, nights were brutal and mentally exhausting.

3 Psychologists who later studied Elena's case noted that her mental strength was just as critical as her physical preparation. "What distinguishes survivors like Elena is not luck," said Dr. Miguel Ferrara of the University of Santiago, "but a mystical level of determination combined with practical problem-solving." Elena herself described certain moments as almost enchanted — a strange calm that descended when panic would have been more expected.

4 When rescuers finally located her, they were astonished to find her in a relatively stable condition, though severely malnourished. Elena's story quickly became an inspiring case study in survival psychology. She later gave talks at medical schools and outdoor training programmes, sharing what she had learned about the human body's resilience and the power of routine in keeping despair at bay.

5 Today, Elena still leads hiking expeditions in Patagonia. She insists that her experience did not make her fearful of the mountains — quite the opposite. "The mountains gave me back something I didn't know I had lost," she says. Her story reminds us that the most inspiring individuals are not those who avoid adversity, but those who find a way through it.

TEXT II: When Talent Meets the Right Moment: Life Lessons from Sport
1 Every athlete who reaches the top of their sport will tell you the same thing: talent alone is never enough. The sports world is filled with stories of gifted individuals who never fulfilled their potential, and of seemingly ordinary players who went on to achieve extraordinary things. What makes the difference? Most coaches, psychologists, and athletes agree that it comes down to a combination of discipline, timing, and the ability to learn from both victory and defeat.

2 Take the case of Amara Diallo, a Senegalese long-distance runner who showed little promise in her early teens. Her times were not impressive, and her technique was considered rough. But her coach, rather than dismissing her, began working with her on her mental approach. They focused on breathing exercises, post-race reflection, and what her coach called "the discipline of the small win" — finding something positive in every session, no matter how modest. The results were gradual, but the trajectory was dramatic. By the age of twenty-four, Amara had won two continental gold medals.

3 Sport teaches lessons that extend far beyond the track or field. The ability to remain fresh and focused during pressure is one of the most transferable skills an athlete can develop. Sports psychologists often describe this as a "lively mind" — one that stays alert and engaged rather than becoming dulled by repetition or anxiety. Athletes who develop this quality tend to perform better not only in competition but also in academic and professional environments.

4 There is also the question of timing. Even the most talented individuals need the right conditions to flourish. A player who enters a team at the wrong moment — when leadership is poor, resources are scarce, or team culture is toxic — may struggle despite genuine ability. Conversely, a player of modest talent who arrives at the right time, surrounded by the right people, can achieve results that surprise everyone, including themselves.

5 Ultimately, sport offers a compressed version of life's most fundamental lessons: work consistently, stay curious, embrace failure as feedback, and recognise that no achievement happens in isolation. These are not just lessons for athletes. They are lessons for anyone who wants to grow.

TEXT III: A World of Choices: How Chance and Culture Shape What We Eat
1 Food is one of the most powerful expressions of culture, identity, and geography. Across the globe, the ingredients people grow, cook, and share tell stories of migration, tradition, and adaptation. What one community considers an everyday staple, another may regard as exotic or even strange. From the fresh herbs piled high in a Moroccan souk to the tender artichokes grilled over coals in a Turkish village, the world's kitchens reveal the extraordinary variety of human experience.

2 In many parts of the world, what people eat is as much a matter of chance as choice. Geography, climate, and historical trade routes determine which ingredients are available. A community living near the sea will naturally build its cuisine around fish and salt. A landlocked mountain village will rely on preserved meats, root vegetables, and hearty grains. These conditions are not chosen — they are inherited, and they shape taste, technique, and food culture for generations.

3 When cultures come into contact, food transforms. The tomato, now considered quintessentially Italian, arrived in Europe from the Americas only in the sixteenth century. Chillies, which give so many Asian dishes their characteristic heat, followed the same route. In Japan, the technique of deep-frying — known as tempura — was introduced by Portuguese missionaries in the sixteenth century. These crossings show that the dishes we consider "traditional" are often the result of dramatic, unpredictable encounters between worlds.

4 Today, globalisation has accelerated this process. A street vendor in Bangkok may sell dishes that contain ingredients from three different continents. A chef in London might grate cured Spanish cheese over a pasta dish using techniques learned in Tokyo. Meanwhile, food tourism has grown into a major industry, with millions of travellers each year choosing destinations specifically to taste and explore local culinary traditions. Yet this same globalisation raises concerns: as international food brands spread, unique regional flavours risk being lost forever.

5 Perhaps the most interesting aspect of food culture today is the tension between the global and the local. On one hand, people increasingly want access to diverse, international flavours. On the other, there is a growing movement to protect traditional foods — including legally recognised labels for products like Champagne, Parmesan, and Darjeeling tea — that can only be produced in specific regions. This tension is unlikely to be resolved. But it ensures that food remains one of the most dynamic, contested, and endlessly fascinating dimensions of human life.\`,
    difficulty: 'medium',
    grammarFocus: 'Reading Comprehension',
    questions: [
      { id: 'blm4-q41', type: 'multiple_choice', question: 'TEXT I, Q1: The main idea of the text is that Elena Vargas _______.', options: ['demonstrates how physical/mental strength can help overcome extreme adversity', 'was an experienced guide who became lost due to poor planning', 'proved that survival in the wild depends mainly on modern equipment', 'was rescued thanks to an enchanted discovery by mountain guides'], correctAnswer: 0, explanation: 'The text highlights her mental/physical strength in surviving.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q42', type: 'multiple_choice', question: 'TEXT I, Q2: According to the text, Elena\\'s psychological state during the ordeal was _______.', options: ['constantly panicked and difficult to control', 'shaped by moments of strange calm alongside exhausting nights', 'relaxed and unaffected by the dangerous conditions', 'too lively to allow her to focus on survival tasks'], correctAnswer: 1, explanation: 'The text mentions strange calm and brutal exhausting nights.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q43', type: 'multiple_choice', question: 'TEXT I, Q3: We can infer from the text that Elena\\'s survival was mainly due to _______.', options: ['luck and the mild weather that followed the blizzard', 'her rich supply of modern rescue technology', 'a combination of prior knowledge, routine, and mental determination', 'assistance she received from other hikers she encountered'], correctAnswer: 2, explanation: 'She used knowledge of plants, built a shelter, and had a strict routine/mental determination.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q44', type: 'multiple_choice', question: 'TEXT I, Q4: The word "captivate" in paragraph 2 is closest in meaning to _______.', options: ['confuse deeply', 'attract and hold great interest', 'frighten and isolate', 'challenge and discourage'], correctAnswer: 1, explanation: 'Captivate means to attract and hold interest.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q45', type: 'multiple_choice', question: 'TEXT I, Q5: "She" in paragraph 5 refers to _______.', options: ['the mountain', 'a medical student', 'the rescue team leader', 'Elena Vargas'], correctAnswer: 3, explanation: 'It refers to Elena Vargas.', difficulty: 'easy', grammarFocus: 'Reading Comprehension' },
      
      { id: 'blm4-q46', type: 'multiple_choice', question: 'TEXT II, Q6: The main idea of the text is that _______.', options: ['Amara Diallo is proof that African athletes are more mentally resilient than others', 'sport shows that success depends on talent, mental strength, timing, and environment', 'the best athletes are those who begin training at a very young age', 'sports psychologists are the most important factor in an athlete\\'s development'], correctAnswer: 1, explanation: 'The text discusses talent, mental discipline, and right timing/environment.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q47', type: 'multiple_choice', question: 'TEXT II, Q7: According to paragraph 2, Amara\\'s coach believed that _______.', options: ['rough technique was more important to fix than mental approach', 'Amara\\'s talent was too limited to produce results', 'building confidence through small positive steps could transform performance', 'long-distance running was unsuitable for athletes from Senegal'], correctAnswer: 2, explanation: 'The discipline of the small win transformed her performance.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q48', type: 'multiple_choice', question: 'TEXT II, Q8: The phrase "lively mind" in paragraph 3 refers to _______.', options: ['a mind that is overexcited and difficult to control in pressure situations', 'a fresh approach to learning that only gifted athletes naturally possess', 'a rich inner world that athletes use to escape from competitive anxiety', 'an alert and engaged mental state that helps performance under stress'], correctAnswer: 3, explanation: 'A mind that stays alert and engaged.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q49', type: 'multiple_choice', question: 'TEXT II, Q9: We can infer from paragraph 4 that a talented player may underperform because _______.', options: ['they lack a competitive and lively personality', 'the surrounding team environment can significantly affect individual results', 'timing is less important than the level of physical conditioning', 'coaches consistently fail to recognise genuine ability'], correctAnswer: 1, explanation: 'Right timing and environment are necessary; a toxic culture can hinder success.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q50', type: 'multiple_choice', question: 'TEXT II, Q10: "They" in paragraph 5 refers to _______.', options: ['life\\'s most fundamental lessons', 'sports psychologists', 'athletes who embrace failure', 'academic and professional environments'], correctAnswer: 0, explanation: 'Refers to the fundamental lessons learned from sport.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },

      { id: 'blm4-q51', type: 'multiple_choice', question: 'TEXT III, Q11: What is the main idea of the text?', options: ['Modern food is becoming unhealthy because of globalisation.', 'Food choices are mainly based on personal preference.', 'Food culture is shaped by geography, history, and cultural contact.', 'Traditional foods are disappearing in all parts of the world.'], correctAnswer: 2, explanation: 'The text is about how geography and history shape what we eat.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q52', type: 'multiple_choice', question: 'TEXT III, Q12: According to paragraph 2, what mainly determines what people eat in different regions?', options: ['Personal taste and cooking skills', 'Geography, climate, and historical conditions', 'Global food trends and tourism', 'Government rules about food production'], correctAnswer: 1, explanation: 'Geography, climate, and trade routes determine ingredients.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q53', type: 'multiple_choice', question: 'TEXT III, Q13: What can be inferred from paragraph 3 about traditional foods?', options: ['They have always stayed the same over time.', 'They often developed through contact with other cultures.', 'They are usually created by local farmers only.', 'They are less important today than in the past.'], correctAnswer: 1, explanation: 'Traditional foods are the result of encounters between worlds.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q54', type: 'multiple_choice', question: 'TEXT III, Q14: In paragraph 4, what does the word "this process" refer to ______?', options: ['The loss of regional flavours', 'The spread of international food brands', 'The mixing of foods and cooking traditions from different cultures', 'The growth of food tourism as an industry'], correctAnswer: 2, explanation: 'It refers to the transformation and mixing of food cultures.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
      { id: 'blm4-q55', type: 'multiple_choice', question: 'TEXT III, Q15: "That" in paragraph 5 refers to ______?', options: ['The tension between global and local food', 'International flavours', 'Traditional foods such as Champagne, Parmesan, and Darjeeling tea', 'Legal systems protecting food culture'], correctAnswer: 2, explanation: 'It refers to labels/products that can only be produced in specific regions.', difficulty: 'medium', grammarFocus: 'Reading Comprehension' },
    ],
  }
`;

fs.writeFileSync('scratch/b_level_m4.js', examSets);
